basePath: /service
definitions:
  model.KeyResult:
    properties:
      created_at:
        type: string
      current_value:
        type: integer
      id:
        type: integer
      initial_value:
        type: integer
      key_result_values:
        items:
          $ref: "#/definitions/model.KeyResultValue"
        type: array
      memo:
        type: string
      objective_id:
        type: integer
      sequence:
        type: integer
      tag:
        type: string
      target_value:
        type: integer
      title:
        type: string
      todos:
        items:
          $ref: "#/definitions/model.Todo"
        type: array
      topic:
        type: string
      uid:
        type: string
      updated_at:
        type: string
      value_mode:
        $ref: "#/definitions/model.ValueModeType"
    type: object
  model.KeyResultValue:
    properties:
      created_at:
        type: string
      id:
        type: integer
      key_result_id:
        type: integer
      memo:
        type: string
      updated_at:
        type: string
      value:
        type: integer
    type: object
  model.Objective:
    properties:
      created_data:
        type: string
      current_value:
        type: integer
      feasibility:
        type: string
      id:
        type: integer
      is_plan:
        type: integer
      key_results:
        items:
          $ref: "#/definitions/model.KeyResult"
        type: array
      memo:
        type: string
      motive:
        type: string
      plan_end:
        type: string
      plan_start:
        type: string
      progress:
        type: integer
      reviews:
        items:
          $ref: "#/definitions/model.Review"
        type: array
      sequence:
        type: integer
      tag:
        type: string
      title:
        type: string
      topic:
        type: string
      total_value:
        type: integer
      uid:
        type: string
      updated_date:
        type: string
    type: object
  model.Review:
    properties:
      created_at:
        type: string
      evaluations:
        items:
          $ref: "#/definitions/model.ReviewEvaluation"
        type: array
      id:
        type: integer
      objective_id:
        type: integer
      rating:
        type: integer
      topic:
        type: string
      type:
        $ref: "#/definitions/model.ReviewType"
      uid:
        type: string
      updated_at:
        type: string
    type: object
  model.ReviewEvaluation:
    properties:
      created_at:
        type: string
      id:
        type: integer
      question:
        type: string
      reason:
        type: string
      review_id:
        type: integer
      solving:
        type: string
      topic:
        type: string
      uid:
        type: string
      updated_at:
        type: string
    type: object
  model.ReviewType:
    enum:
      - 0
      - 1
      - 2
    type: integer
    x-enum-varnames:
      - ReviewTypeUnknown
      - ReviewMid
      - ReviewEnd
  model.Todo:
    properties:
      category:
        type: string
      complete:
        type: integer
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      is_remind_at_time:
        type: integer
      key_result_id:
        type: integer
      parent_id:
        type: integer
      priority:
        type: integer
      remark:
        type: string
      remind_at:
        type: integer
      repeat_end_at:
        type: integer
      repeat_method:
        type: string
      repeat_rule:
        type: string
      sequence:
        type: integer
      sub_todos:
        items:
          $ref: "#/definitions/model.Todo"
        type: array
      topic:
        type: string
      uid:
        type: string
      updated_at:
        type: string
    type: object
  model.ValueModeType:
    enum:
      - sum
      - last
      - avg
      - max
    type: string
    x-enum-varnames:
      - ValueSumMode
      - ValueLastMode
      - ValueAvgMode
      - ValueMaxMode
  protocol.Response:
    properties:
      data:
        description: Response data
      message:
        description: |-
          Error message, it is recommended to fill in a human-readable error message when the action fails to execute,
          or an empty string when it succeeds.
        type: string
      retcode:
        description:
          The return code, which must conform to the return code rules
          defined later on this page
        type: string
      status:
        allOf:
          - $ref: "#/definitions/protocol.ResponseStatus"
        description: |-
          Execution status (success or failure), must be one of ok and failed,
          indicating successful and unsuccessful execution, respectively.
    type: object
  protocol.ResponseStatus:
    enum:
      - ok
      - failed
    type: string
    x-enum-varnames:
      - Success
      - Failed
  types.KV:
    additionalProperties: true
    type: object
host: localhost:6060
info:
  contact: {}
  description: Flowbot Chatbot API
  license:
    name: GPL 3.0
    url: https://github.com/flowline-io/flowbot/blob/master/LICENSE
  title: Flowbot API
  version: "1.0"
paths:
  /dev/example:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/types.KV"
                type: object
      summary: Show example
      tags:
        - dev
  /okr/key_result:
    post:
      consumes:
        - application/json
      parameters:
        - description: KeyResult data
          in: body
          name: keyResult
          required: true
          schema:
            $ref: "#/definitions/model.KeyResult"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/protocol.Response"
      security:
        - ApiKeyAuth: []
      summary: KeyResult create
      tags:
        - okr
  /okr/key_result/{id}/value:
    post:
      consumes:
        - application/json
      parameters:
        - description: key result id
          in: path
          name: id
          required: true
          type: integer
        - description: KeyResultValue data
          in: body
          name: KeyResultValue
          required: true
          schema:
            $ref: "#/definitions/model.KeyResultValue"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/protocol.Response"
      security:
        - ApiKeyAuth: []
      summary: KeyResult value create
      tags:
        - okr
  /okr/key_result/{id}/values:
    get:
      consumes:
        - application/json
      parameters:
        - description: key result id
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    items:
                      $ref: "#/definitions/model.KeyResultValue"
                    type: array
                type: object
      security:
        - ApiKeyAuth: []
      summary: key result value list
      tags:
        - okr
  /okr/key_result/{sequence}:
    delete:
      consumes:
        - application/json
      parameters:
        - description: Sequence
          in: path
          name: sequence
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/protocol.Response"
      security:
        - ApiKeyAuth: []
      summary: KeyResult delete
      tags:
        - okr
    put:
      consumes:
        - application/json
      parameters:
        - description: Sequence
          in: path
          name: sequence
          required: true
          type: integer
        - description: KeyResult data
          in: body
          name: objective
          required: true
          schema:
            $ref: "#/definitions/model.KeyResult"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/protocol.Response"
      security:
        - ApiKeyAuth: []
      summary: KeyResult update
      tags:
        - okr
  /okr/key_result_value/{id}:
    delete:
      consumes:
        - application/json
      parameters:
        - description: key result id
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/protocol.Response"
      security:
        - ApiKeyAuth: []
      summary: KeyResult value delete
      tags:
        - okr
    get:
      consumes:
        - application/json
      parameters:
        - description: key result id
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/model.KeyResultValue"
                type: object
      security:
        - ApiKeyAuth: []
      summary: KeyResult value detail
      tags:
        - okr
  /okr/objective:
    post:
      consumes:
        - application/json
      parameters:
        - description: objective data
          in: body
          name: objective
          required: true
          schema:
            $ref: "#/definitions/model.Objective"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/protocol.Response"
      security:
        - ApiKeyAuth: []
      summary: objective create
      tags:
        - okr
  /okr/objective/{sequence}:
    delete:
      consumes:
        - application/json
      parameters:
        - description: Sequence
          in: path
          name: sequence
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/protocol.Response"
      security:
        - ApiKeyAuth: []
      summary: objective delete
      tags:
        - okr
    get:
      consumes:
        - application/json
      parameters:
        - description: Sequence
          in: path
          name: sequence
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/model.Objective"
                type: object
      security:
        - ApiKeyAuth: []
      summary: objective detail
      tags:
        - okr
    put:
      consumes:
        - application/json
      parameters:
        - description: Sequence
          in: path
          name: sequence
          required: true
          type: integer
        - description: objective data
          in: body
          name: objective
          required: true
          schema:
            $ref: "#/definitions/model.Objective"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/protocol.Response"
      security:
        - ApiKeyAuth: []
      summary: objective update
      tags:
        - okr
  /okr/objectives:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    items:
                      $ref: "#/definitions/model.Objective"
                    type: array
                type: object
      security:
        - ApiKeyAuth: []
      summary: objective list
      tags:
        - okr
  /search/autocomplete:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/types.KV"
                type: object
      security:
        - ApiKeyAuth: []
      summary: search autocomplete
      tags:
        - search
  /search/query:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/types.KV"
                type: object
      security:
        - ApiKeyAuth: []
      summary: search everything
      tags:
        - search
  /server/stacktrace:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/types.KV"
                type: object
      security:
        - ApiKeyAuth: []
      summary: get server or goroutines stacktrace
      tags:
        - dev
  /server/upload:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/types.KV"
                type: object
      security:
        - ApiKeyAuth: []
      summary: upload PicGO upload api
      tags:
        - dev
  /user/bookmark:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/types.KV"
                type: object
      security:
        - ApiKeyAuth: []
      summary: get user bookmark list
      tags:
        - user
  /user/dashboard:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/types.KV"
                type: object
      security:
        - ApiKeyAuth: []
      summary: Show dashboard
      tags:
        - user
  /user/kanban:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/types.KV"
                type: object
      security:
        - ApiKeyAuth: []
      summary: get user kanban list
      tags:
        - user
  /user/metrics:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/protocol.Response"
              - properties:
                  data:
                    $ref: "#/definitions/types.KV"
                type: object
      security:
        - ApiKeyAuth: []
      summary: Show metrics
      tags:
        - user
schemes:
  - http
securityDefinitions:
  ApiKeyAuth:
    description: access token
    in: header
    name: X-AccessToken
    type: apiKey
swagger: "2.0"
